# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 90, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 160, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 280, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 360, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtplanttext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtplanttext.setGeometry(QtCore.QRect(170, 150, 511, 71))
        self.txtplanttext.setObjectName("txtplanttext")
        self.txtkey = QtWidgets.QLineEdit(self.centralwidget)
        self.txtkey.setGeometry(QtCore.QRect(170, 280, 511, 20))
        self.txtkey.setObjectName("txtkey")
        self.txtciphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtciphertext.setGeometry(QtCore.QRect(173, 340, 511, 71))
        self.txtciphertext.setObjectName("txtciphertext")
        self.btnencrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnencrypt.setGeometry(QtCore.QRect(250, 482, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnencrypt.setFont(font)
        self.btnencrypt.setObjectName("btnencrypt")
        self.btndecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btndecrypt.setGeometry(QtCore.QRect(460, 482, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btndecrypt.setFont(font)
        self.btndecrypt.setObjectName("btndecrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plan Text"))
        self.label_3.setText(_translate("MainWindow", "Key"))
        self.label_4.setText(_translate("MainWindow", "Cipher Text"))
        self.btnencrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btndecrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
